import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Crear_grupo from '../../components/contenedor_crear_grupo'

export default function Home() {
	return (
		<div>
			<Head>
				<title>Chat anónimo</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/chuerk.png" />
			</Head>

			<div className={styles.container}>
				<main className={styles.main}>
					<Crear_grupo />
				</main>
			</div>
			<footer className={styles.footer}>
        		<p>Me pica la cola</p>
      		</footer>
		</div>
	)
}