import React,{ useState, useEffect, useContext } from 'react'
export default function ver_miembros(id_g){

    const [grupoinfo, setgrupoinfo] = useState([]);

    useEffect( async () =>{ 
        //event.preventDefault()
        const url = process.env.URL_BACKEND + '/grupo/getGrupo'
        const res = await fetch(url, {
          body: JSON.stringify({
            grupo_id: id_g
          }),
          headers: {
            'Content-Type': 'application/json; charset=utf-8'
          },
          method: 'POST'
        })

        const json =  await res.json()
        setgrupoinfo(json.info_grupo)
        //console.log(json.info_grupo) 
    })

    return (
        <div>
            <Head>
                <title>Chat anónimo</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/chuerk.png" />
            </Head>

            <div className={styles.container}>
                <main className={styles.reg}>
                    <Contenedor_reg />
                </main>
            </div>
        </div>
        
    )

}